#!/usr/bin/env node
/**
 * SA4 Report Template -- release bundle builder.
 * PROTOTYPE (design/report-template-architecture). See
 * docs/SA4_REPORT_TEMPLATE_ARCHITECTURE.md §10.
 *
 * Assembles the exact files for the master template's bound script into
 * dist/template-release/<releaseId>/ together with a generated Release.js,
 * a .clasp.json for the TEMPLATE script only, a whitelisting .claspignore
 * and RELEASE-MANIFEST.json (sha256 per file).
 *
 * It never runs clasp and never talks to Google. It prints the one command
 * to run from the bundle directory after review.
 *
 *   node tools/template-release.js --release T-2026.10.0            (dry run)
 *   node tools/template-release.js --release T-2026.10.0 --write    (bundle)
 *
 * Guardrails (each one is a real past or near-miss incident):
 *   - the target Script ID must come from template/template-target.json and
 *     must not be the Legacy or CENTRAL project (sa4-report/.clasp.json
 *     itself points at Legacy today);
 *   - only whitelisted runtime files are bundled -- never tests/ (LEGACY-
 *     UPGRADE-002: leaked test files with require() broke onOpen);
 *   - the working tree must be clean and HEAD must carry the tag
 *     template-release/<releaseId>, so every template state maps to Git;
 *   - Release.js records releaseId + commit, and the report's first run
 *     copies it into Document Properties.
 */

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { execFileSync } = require('child_process');

const REPO_ROOT = path.join(__dirname, '..');

// Projects that must never receive a template push. They are listed by the
// SHA-256 digest of their Script ID, not by the ID itself: this file is
// public, the IDs are not. A target is protected when its digest matches.
const PROTECTED_PROJECT_LABELS = {
  legacy: 'Legacy bound script (6G Media Minutes, meeting 86178)',
  central: 'CENTRAL editor add-on'
};
const PROTECTED_SCRIPT_ID_DIGESTS = {
  legacy: '0b5b6122b8c4d661e5c9ce65542441ca724c93880a8c5f15e371cbbc576c556b',
  central: 'a536eb96d5a5ec45b1275a76b56afde4cbadd3c083ec44126da2ef6107c6268d'
};
const scriptIdDigest = (id) => crypto.createHash('sha256').update(String(id === null || id === undefined ? '' : id)).digest('hex');

/** A digest table for the given Script IDs -- for the tests, which use synthetic IDs. */
function protectionForScriptIds(ids) {
  return { legacy: scriptIdDigest(ids.legacy), central: scriptIdDigest(ids.central) };
}

/** 'legacy', 'central' or null. `protection` defaults to the built-in digests. */
function protectedProjectKey(id, protection) {
  const table = protection || PROTECTED_SCRIPT_ID_DIGESTS;
  const idDigest = scriptIdDigest(id);
  return Object.keys(table).find((key) => table[key] === idDigest) || null;
}

/** The name of the protected project a Script ID belongs to, or null. */
function protectedProject(id, protection) {
  const key = protectedProjectKey(id, protection);
  return key ? PROTECTED_PROJECT_LABELS[key] : null;
}

// Repository path -> published file name. Nothing else is ever bundled.
const RELEASE_FILES = [
  ['appsscript.json', 'appsscript.json'],
  ['Code.js', 'Code.js'],
  ['HyperLink.js', 'HyperLink.js'],
  ['colab_notebook.html', 'colab_notebook.html'],
  ['colab_notebook_shared.html', 'colab_notebook_shared.html'],
  ['template/ReportCreator.js', 'ReportCreator.js']
];

const RELEASE_ID_RE = /^T-\d{4}\.\d{2}\.\d+$/;
const SCRIPT_ID_RE = /^[A-Za-z0-9_-]{40,80}$/;
const DRIVE_ID_RE = /^[A-Za-z0-9_-]{25,100}$/;

function validateTarget(target, protection) {
  const errors = [];
  if (!target || typeof target !== 'object') return ['template/template-target.json is missing or not an object.'];
  if (!SCRIPT_ID_RE.test(String(target.templateScriptId || ''))) errors.push('templateScriptId is missing or malformed.');
  if (!DRIVE_ID_RE.test(String(target.templateDocumentId || ''))) errors.push('templateDocumentId is missing or malformed.');
  const protectedAs = protectedProject(target.templateScriptId, protection);
  if (protectedAs) {
    errors.push('templateScriptId is the ' + protectedAs + ' -- refusing.');
  }
  return errors;
}

function buildReleaseJs(meta) {
  return '/**\n * GENERATED by tools/template-release.js -- do not edit.\n' +
    ' * Present only in SA4 Report Template release bundles.\n */\n' +
    'var SA4_RELEASE_ = ' + JSON.stringify(meta, null, 2) + ';\n';
}

function buildClaspIgnore(publishedNames) {
  return ['**/**'].concat(publishedNames.map((n) => '!' + n)).join('\n') + '\n';
}

/**
 * Pure release plan. git: { commit, dirty, tagsAtHead }. readFile(relPath)
 * returns the file content (Buffer or string) or throws.
 */
function planRelease({ releaseId, target, git, readFile, builtAt, protection }) {
  const errors = [];
  if (!RELEASE_ID_RE.test(String(releaseId || ''))) errors.push('--release must look like T-2026.10.0.');
  errors.push(...validateTarget(target, protection));
  if (!git || !/^[0-9a-f]{40}$/.test(String(git.commit || ''))) errors.push('Could not read the HEAD commit.');
  if (git && git.dirty) errors.push('The working tree is not clean -- commit or stash first.');
  const tag = 'template-release/' + releaseId;
  if (git && (git.tagsAtHead || []).indexOf(tag) === -1) errors.push('HEAD is not tagged ' + tag + '.');

  const files = [];
  RELEASE_FILES.forEach(([src, name]) => {
    let content;
    try { content = readFile(src); } catch (e) { errors.push('Missing release file ' + src + '.'); return; }
    files.push({ name, source: src, content });
  });
  const manifestFile = files.find((f) => f.name === 'appsscript.json');
  if (manifestFile) {
    try {
      const manifest = JSON.parse(String(manifestFile.content));
      if (manifest.addOns) errors.push('appsscript.json declares addOns -- the template runtime is a bound script, not an add-on.');
    } catch (e) {
      errors.push('appsscript.json is not valid JSON.');
    }
  }
  files.forEach((f) => {
    if (/\brequire\s*\(/.test(String(f.content)) && /\.js$/.test(f.name)) {
      errors.push(f.name + ' calls require() -- Node-only code would break onOpen in Apps Script.');
    }
  });

  const meta = {
    releaseId,
    flavor: 'template',
    gitCommit: git ? git.commit : null,
    gitTag: tag,
    builtAt,
    templateDocumentId: target ? target.templateDocumentId : null,
    templateScriptId: target ? target.templateScriptId : null
  };
  files.push({ name: 'Release.js', source: '(generated)', content: buildReleaseJs(meta) });

  const published = files.map((f) => f.name);
  return {
    ok: errors.length === 0,
    errors,
    meta,
    files,
    claspJson: target ? JSON.stringify({ scriptId: target.templateScriptId, rootDir: '.' }, null, 2) + '\n' : null,
    claspIgnore: buildClaspIgnore(published),
    manifest: {
      releaseId,
      gitCommit: meta.gitCommit,
      templateScriptId: meta.templateScriptId,
      files: files.map((f) => ({ name: f.name, source: f.source, sha256: crypto.createHash('sha256').update(f.content).digest('hex') }))
    }
  };
}

function readGit() {
  const run = (args) => execFileSync('git', args, { cwd: REPO_ROOT, encoding: 'utf8' }).trim();
  return {
    commit: run(['rev-parse', 'HEAD']),
    dirty: run(['status', '--porcelain']) !== '',
    tagsAtHead: run(['tag', '--points-at', 'HEAD']).split(/\r?\n/).filter(Boolean)
  };
}

function main(argv) {
  const args = { write: argv.includes('--write') };
  const i = argv.indexOf('--release');
  args.release = i !== -1 ? argv[i + 1] : null;

  const targetPath = path.join(REPO_ROOT, 'template', 'template-target.json');
  let target = null;
  try { target = JSON.parse(fs.readFileSync(targetPath, 'utf8')); } catch (e) { /* reported by validateTarget */ }

  const plan = planRelease({
    releaseId: args.release,
    target,
    git: readGit(),
    readFile: (rel) => fs.readFileSync(path.join(REPO_ROOT, rel)),
    builtAt: new Date().toISOString()
  });

  plan.files.forEach((f) => console.log('  ' + f.name.padEnd(28) + ' <- ' + f.source));
  if (!plan.ok) {
    console.error('\nRelease refused:\n' + plan.errors.map((e) => '  - ' + e).join('\n'));
    return 1;
  }
  const outDir = path.join(REPO_ROOT, 'dist', 'template-release', args.release);
  if (!args.write) {
    console.log('\nDry run OK. Re-run with --write to create ' + path.relative(REPO_ROOT, outDir));
    return 0;
  }
  if (fs.existsSync(outDir)) {
    console.error('\n' + outDir + ' already exists -- a release bundle is never overwritten.');
    return 1;
  }
  fs.mkdirSync(outDir, { recursive: true });
  plan.files.forEach((f) => fs.writeFileSync(path.join(outDir, f.name), f.content));
  fs.writeFileSync(path.join(outDir, '.clasp.json'), plan.claspJson);
  fs.writeFileSync(path.join(outDir, '.claspignore'), plan.claspIgnore);
  fs.writeFileSync(path.join(outDir, 'RELEASE-MANIFEST.json'), JSON.stringify(plan.manifest, null, 2) + '\n');
  console.log('\nBundle written to ' + outDir);
  console.log('Review it, then push to the TEMPLATE project only:');
  console.log('  cd "' + outDir + '" && clasp push');
  return 0;
}

if (require.main === module) process.exitCode = main(process.argv.slice(2));

module.exports = {
  planRelease, validateTarget, buildReleaseJs, buildClaspIgnore, RELEASE_FILES,
  PROTECTED_SCRIPT_ID_DIGESTS, PROTECTED_PROJECT_LABELS, protectionForScriptIds, protectedProject, protectedProjectKey
};
